In [10]:
import shutil
import warnings
import sys

shutil.copy2('./../../myCBR_projects/userKnowledgeModeling_yedek.prj', './../../myCBR_projects/userKnowledgeModeling.prj') # complete target filename given

warnings.filterwarnings("ignore")
sys.path.append('../../')
sys.path.append('../')

In [2]:
import random
import pickle
from PertCF import *

In [3]:
# Set random seed
random_state = random.randint(0, 100)

# Concept name
concept = 'knowledge'
column_names = ['STG','SCG','STR','LPR','PEG','UNS']
class_names = ['0','1','2','3']
cat_feat = []

# Read data
train = pd.read_pickle('./Data/unm_train.pkl')
test =  pd.read_pickle('./Data/unm_test.pkl')

train_cols = train.columns[0:-1]
label = train.columns[-1]

X_train, X_test, y_train, y_test = train[train_cols], test[train_cols], train[[label]], test[[label]]

In [4]:
def rev(dic):
    return {v: k for k, v in dic.items()}

# from categoric features to numeric features with maps
# from numeric features to categoric features with inv_maps
def encode(df, maps):
    for i in cat_feat:
        df[i] = df[i].map(maps[i]).astype('float')
    return df

maps = {}
inv_maps = {}

# encoding for training the model
#X_en = encode(X.copy(), maps)
X_train_en, X_test_en = encode(X_train.copy(), maps), encode(X_test.copy(), maps)
train_en = encode(train.copy(), maps)
test_en = encode(test.copy(), maps)

# load model
model = pickle.load(open('./Model/model_GBC.pkl', "rb"))

# load shap_df
shap_df = pd.read_pickle("./temp_files/shap_df.pkl")

In [5]:
num_iter = 10
explainer = Explainer(model, X_train, X_test, y_train, y_test, label, cat_feat, concept, shap_df=shap_df, maps=maps, inv_maps=inv_maps, num_iter=num_iter)

Given Shap values used.

API connection completed.

Concept names:  ['knowledge']  Is correct:  True

Casebase names:  [['cb_class1'], ['cb_class0'], ['cb_class3'], ['cb_class2']]

Cases deleted from concept 'knowledge': True

Cases imported to the casebases.

Amalgamation functions created for every class using shap values.

In [8]:
res_list_names = ['coef', 'num_iter', 'dissimilarity', 'sparsity', 'instability', 'time']
res_list = []


for coef in [1,2,3,4,5,6,7,8,9,10,25,50,75,100,150,200,300,400,500,750]:
    _, res = explainer.testGenerateCF(coef_thresh = coef)
    res_list.append([coef]+[num_iter]+res)

res_df = pd.DataFrame(res_list,columns=res_list_names)

1
2
3
4
5

In [9]:
res_df

   coef  num_iter  dissimilarity  sparsity  instability      time
0     1        10       0.061471  0.058537      0.06424  0.710118
1     2        10       0.061471  0.058537      0.06424  0.668731
2     3        10       0.061471  0.058537      0.06424  0.641808
3     4        10       0.061471  0.058537      0.06424  0.662547
4     5        10       0.061471  0.058537      0.06424  0.675083

In [8]:
#res_df.to_pickle('./Output/exp1_coef_1-750_numIter_10.pkl')

----

In [9]:
shutil.copy2('./../../myCBR_projects/userKnowledgeModeling_yedek.prj', './../../myCBR_projects/userKnowledgeModeling.prj') # complete target filename given

In [11]:
# Set random seed
random_state = random.randint(0, 100)

# Concept name
concept = 'knowledge'
column_names = ['STG','SCG','STR','LPR','PEG','UNS']
class_names = ['0','1','2','3']
cat_feat = []

# Read data
train = pd.read_pickle('./Data/unm_train.pkl')
test =  pd.read_pickle('./Data/unm_test.pkl')

train_cols = train.columns[0:-1]
label = train.columns[-1]

X_train, X_test, y_train, y_test = train[train_cols], test[train_cols], train[[label]], test[[label]]

In [12]:
def rev(dic):
    return {v: k for k, v in dic.items()}

# from categoric features to numeric features with maps
# from numeric features to categoric features with inv_maps
def encode(df, maps):
    for i in cat_feat:
        df[i] = df[i].map(maps[i]).astype('float')
    return df

maps = {}
inv_maps = {}

# encoding for training the model
#X_en = encode(X.copy(), maps)
X_train_en, X_test_en = encode(X_train.copy(), maps), encode(X_test.copy(), maps)
train_en = encode(train.copy(), maps)
test_en = encode(test.copy(), maps)

# load model
model = pickle.load(open('./Model/model_GBC.pkl', "rb"))

# load shap_df
shap_df = pd.read_pickle("./temp_files/shap_df.pkl")

In [13]:
num_iter = 5
explainer = Explainer(model, X_train, X_test, y_train, y_test, label, cat_feat, concept, shap_df=shap_df, maps=maps, inv_maps=inv_maps, num_iter=num_iter)

Given Shap values used.

API connection completed.

Concept names:  ['knowledge']  Is correct:  True

Casebase names:  [['cb_class1'], ['cb_class0'], ['cb_class3'], ['cb_class2']]

Cases deleted from concept 'knowledge': True

Cases imported to the casebases.

Amalgamation functions created for every class using shap values.

In [14]:
res_list_names = ['coef', 'num_iter', 'dissimilarity', 'sparsity', 'instability', 'time']
res_list = []

for coef in [1,2,3,4,5,6,7,8,9,10,25,50,75,100,150,200,300,400,500,750]:
    _, res = explainer.testGenerateCF(coef_thresh = coef)
    res_list.append([coef]+[num_iter]+res)

res_df = pd.DataFrame(res_list,columns=res_list_names)

1
2
3
4
5
6
7
8
9
10
25
50
75
100
150
200
300
400
500
750

In [15]:
res_df

    coef  num_iter  dissimilarity  sparsity  instability      time
0      1         5       0.063630  0.058537     0.066436  0.441618
1      2         5       0.063630  0.058537     0.066436  0.415979
2      3         5       0.063630  0.058537     0.066436  0.407380
3      4         5       0.063630  0.058537     0.066436  0.423930
4      5         5       0.063630  0.058537     0.066436  0.448127
5      6         5       0.063630  0.058537     0.066436  0.473238
6      7         5       0.063630  0.058537     0.066436  0.498441
7      8         5       0.063630  0.058537     0.066436  0.510467
8      9         5       0.063630  0.058537     0.066436  0.528226
9     10         5       0.063630  0.058537     0.066436  0.564783
10    25         5       0.064005  0.058537     0.066808  0.625831
11    50         5       0.064096  0.058537     0.066896  0.677735
12    75         5       0.064176  0.058537     0.066976  0.688173
13   100         5       0.064192  0.058537     0.066994  0.787049
14   150         5       0.064171  0.058537     0.066973  0.824156
15   200         5       0.064154  0.058537     0.066956  0.858805
16   300         5       0.064154  0.058537     0.066956  0.924832
17   400         5       0.064159  0.058537     0.066960  0.981168
18   500         5       0.064160  0.058537     0.066962  1.034317
19   750         5       0.064160  0.058537     0.066962  1.072101

In [16]:
res_df.to_pickle('./Output/exp1_coef_1-750_numIter_5.pkl')

---

----

In [17]:
shutil.copy2('./../../myCBR_projects/userKnowledgeModeling_yedek.prj', './../../myCBR_projects/userKnowledgeModeling.prj') # complete target filename given

In [19]:
# Set random seed
random_state = random.randint(0, 100)

# Concept name
concept = 'knowledge'
column_names = ['STG','SCG','STR','LPR','PEG','UNS']
class_names = ['0','1','2','3']
cat_feat = []

# Read data
train = pd.read_pickle('./Data/unm_train.pkl')
test =  pd.read_pickle('./Data/unm_test.pkl')

train_cols = train.columns[0:-1]
label = train.columns[-1]

X_train, X_test, y_train, y_test = train[train_cols], test[train_cols], train[[label]], test[[label]]

In [20]:
def rev(dic):
    return {v: k for k, v in dic.items()}

# from categoric features to numeric features with maps
# from numeric features to categoric features with inv_maps
def encode(df, maps):
    for i in cat_feat:
        df[i] = df[i].map(maps[i]).astype('float')
    return df

maps = {}
inv_maps = {}

# encoding for training the model
#X_en = encode(X.copy(), maps)
X_train_en, X_test_en = encode(X_train.copy(), maps), encode(X_test.copy(), maps)
train_en = encode(train.copy(), maps)
test_en = encode(test.copy(), maps)

# load model
model = pickle.load(open('./Model/model_GBC.pkl', "rb"))

# load shap_df
shap_df = pd.read_pickle("./temp_files/shap_df.pkl")

In [21]:
num_iter = 20
explainer = Explainer(model, X_train, X_test, y_train, y_test, label, cat_feat, concept, shap_df=shap_df, maps=maps, inv_maps=inv_maps, num_iter=num_iter)

Given Shap values used.

API connection completed.

Concept names:  ['knowledge']  Is correct:  True

Casebase names:  [['cb_class1'], ['cb_class0'], ['cb_class3'], ['cb_class2']]

Cases deleted from concept 'knowledge': True

Cases imported to the casebases.

Amalgamation functions created for every class using shap values.

In [22]:
res_list_names = ['coef', 'num_iter', 'dissimilarity', 'sparsity', 'instability', 'time']
res_list = []


for coef in [1,2,3,4,5,6,7,8,9,10,25,50,75,100,150,200,300,400,500,750]:
    _, res = explainer.testGenerateCF(coef_thresh = coef)
    res_list.append([coef]+[num_iter]+res)

res_df = pd.DataFrame(res_list,columns=res_list_names)

1
2
3
4
5
6
7
8
9
10
25
50
75
100
150
200
300
400
500
750

In [23]:
res_df

    coef  num_iter  dissimilarity  sparsity  instability      time
0      1        20       0.061384  0.058537     0.064153  0.678094
1      2        20       0.061384  0.058537     0.064153  0.660601
2      3        20       0.061384  0.058537     0.064153  0.669239
3      4        20       0.061384  0.058537     0.064153  0.694705
4      5        20       0.061384  0.058537     0.064153  0.738097
5      6        20       0.061384  0.058537     0.064153  0.724350
6      7        20       0.061384  0.058537     0.064153  0.746147
7      8        20       0.061384  0.058537     0.064153  0.799800
8      9        20       0.061384  0.058537     0.064153  0.850813
9     10        20       0.061384  0.058537     0.064153  0.899945
10    25        20       0.061717  0.058537     0.064485  0.991549
11    50        20       0.061792  0.058537     0.064558  1.116437
12    75        20       0.061895  0.058537     0.064660  1.155262
13   100        20       0.061928  0.058537     0.064694  1.247454
14   150        20       0.061935  0.058537     0.064701  1.386743
15   200        20       0.061913  0.058537     0.064679  1.488555
16   300        20       0.061892  0.058537     0.064658  1.601777
17   400        20       0.061896  0.058537     0.064662  1.733999
18   500        20       0.061897  0.058537     0.064663  1.816418
19   750        20       0.061894  0.058537     0.064660  1.924992

In [24]:
res_df.to_pickle('./Output/exp1_coef_1-750_numIter_20.pkl')

---

---

In [25]:
shutil.copy2('./../../myCBR_projects/userKnowledgeModeling_yedek.prj', './../../myCBR_projects/userKnowledgeModeling.prj') # complete target filename given

In [27]:
# Set random seed
random_state = random.randint(0, 100)

# Concept name
concept = 'knowledge'
column_names = ['STG','SCG','STR','LPR','PEG','UNS']
class_names = ['0','1','2','3']
cat_feat = []

# Read data
train = pd.read_pickle('./Data/unm_train.pkl')
test =  pd.read_pickle('./Data/unm_test.pkl')

train_cols = train.columns[0:-1]
label = train.columns[-1]

X_train, X_test, y_train, y_test = train[train_cols], test[train_cols], train[[label]], test[[label]]

In [28]:
def rev(dic):
    return {v: k for k, v in dic.items()}

# from categoric features to numeric features with maps
# from numeric features to categoric features with inv_maps
def encode(df, maps):
    for i in cat_feat:
        df[i] = df[i].map(maps[i]).astype('float')
    return df

maps = {}
inv_maps = {}

# encoding for training the model
#X_en = encode(X.copy(), maps)
X_train_en, X_test_en = encode(X_train.copy(), maps), encode(X_test.copy(), maps)
train_en = encode(train.copy(), maps)
test_en = encode(test.copy(), maps)

# load model
model = pickle.load(open('./Model/model_GBC.pkl', "rb"))

# load shap_df
shap_df = pd.read_pickle("./temp_files/shap_df.pkl")

In [29]:
num_iter = 50
explainer = Explainer(model, X_train, X_test, y_train, y_test, label, cat_feat, concept, shap_df=shap_df, maps=maps, inv_maps=inv_maps, num_iter=num_iter)

Given Shap values used.

API connection completed.

Concept names:  ['knowledge']  Is correct:  True

Casebase names:  [['cb_class1'], ['cb_class0'], ['cb_class3'], ['cb_class2']]

Cases deleted from concept 'knowledge': True

Cases imported to the casebases.

Amalgamation functions created for every class using shap values.

In [30]:
res_list_names = ['coef', 'num_iter', 'dissimilarity', 'sparsity', 'instability', 'time']
res_list = []


for coef in [1,2,3,4,5,6,7,8,9,10,25,50,75,100,150,200,300,400,500,750]:
    _, res = explainer.testGenerateCF(coef_thresh = coef)
    res_list.append([coef]+[num_iter]+res)

res_df = pd.DataFrame(res_list,columns=res_list_names)

1
2
3
4
5
6
7
8
9
10
25
50
75
100
150
200
300
400
500
750

In [31]:
res_df

    coef  num_iter  dissimilarity  sparsity  instability      time
0      1        50       0.061384  0.058537     0.064153  1.156068
1      2        50       0.061384  0.058537     0.064153  1.193762
2      3        50       0.061384  0.058537     0.064153  1.288712
3      4        50       0.061384  0.058537     0.064153  1.414780
4      5        50       0.061384  0.058537     0.064153  1.510135
5      6        50       0.061384  0.058537     0.064153  1.649071
6      7        50       0.061384  0.058537     0.064153  1.793872
7      8        50       0.061384  0.058537     0.064153  1.900077
8      9        50       0.061384  0.058537     0.064153  2.092511
9     10        50       0.061384  0.058537     0.064153  2.233968
10    25        50       0.061717  0.058537     0.064485  2.391444
11    50        50       0.061792  0.058537     0.064558  2.646089
12    75        50       0.061895  0.058537     0.064660  2.893249
13   100        50       0.061928  0.058537     0.064694  3.181628
14   150        50       0.061935  0.058537     0.064701  3.335692
15   200        50       0.061913  0.058537     0.064679  3.496291
16   300        50       0.061892  0.058537     0.064658  3.742047
17   400        50       0.061896  0.058537     0.064662  4.034506
18   500        50       0.061897  0.058537     0.064663  4.164444
19   750        50       0.061894  0.058537     0.064660  4.408353

In [32]:

res_df.to_pickle('./Output/exp1_coef_1-750_numIter_50.pkl')

---

---

In [33]:
shutil.copy2('./../../myCBR_projects/userKnowledgeModeling_yedek.prj', './../../myCBR_projects/userKnowledgeModeling.prj') # complete target filename given

In [35]:
# Set random seed
random_state = random.randint(0, 100)

# Concept name
concept = 'knowledge'
column_names = ['STG','SCG','STR','LPR','PEG','UNS']
class_names = ['0','1','2','3']
cat_feat = []

# Read data
train = pd.read_pickle('./Data/unm_train.pkl')
test =  pd.read_pickle('./Data/unm_test.pkl')

train_cols = train.columns[0:-1]
label = train.columns[-1]

X_train, X_test, y_train, y_test = train[train_cols], test[train_cols], train[[label]], test[[label]]

In [36]:
def rev(dic):
    return {v: k for k, v in dic.items()}

# from categoric features to numeric features with maps
# from numeric features to categoric features with inv_maps
def encode(df, maps):
    for i in cat_feat:
        df[i] = df[i].map(maps[i]).astype('float')
    return df

maps = {}
inv_maps = {}

# encoding for training the model
#X_en = encode(X.copy(), maps)
X_train_en, X_test_en = encode(X_train.copy(), maps), encode(X_test.copy(), maps)
train_en = encode(train.copy(), maps)
test_en = encode(test.copy(), maps)

# load model
model = pickle.load(open('./Model/model_GBC.pkl', "rb"))

# load shap_df
shap_df = pd.read_pickle("./temp_files/shap_df.pkl")

In [41]:
num_iter = 2
explainer = Explainer(model, X_train, X_test, y_train, y_test, label, cat_feat, concept, shap_df=shap_df, maps=maps, inv_maps=inv_maps, num_iter=num_iter)

Given Shap values used.

API connection completed.

Concept names:  ['knowledge']  Is correct:  True

Casebase names:  [['cb_class1'], ['cb_class0'], ['cb_class3'], ['cb_class2']]

Cases deleted from concept 'knowledge': True

Cases imported to the casebases.

Amalgamation functions created for every class using shap values.

In [42]:
res_list_names = ['coef', 'num_iter', 'dissimilarity', 'sparsity', 'instability', 'time']
res_list = []


for coef in [1,2,3,4,5,6,7,8,9,10,25,50,75,100,150,200,300,400,500,750]:
    _, res = explainer.testGenerateCF(coef_thresh = coef)
    res_list.append([coef]+[num_iter]+res)

res_df = pd.DataFrame(res_list,columns=res_list_names)

1
2
3
4
5
6
7
8
9
10
25
50
75
100
150
200
300
400
500
750

In [43]:
res_df

    coef  num_iter  dissimilarity  sparsity  instability      time
0      1         2       0.075516   0.04878     0.077908  0.465217
1      2         2       0.075516   0.04878     0.077908  0.468089
2      3         2       0.075516   0.04878     0.077908  0.455122
3      4         2       0.075516   0.04878     0.077908  0.442952
4      5         2       0.075516   0.04878     0.077908  0.469162
5      6         2       0.075516   0.04878     0.077908  0.482822
6      7         2       0.075516   0.04878     0.077908  0.519362
7      8         2       0.075516   0.04878     0.077908  0.543795
8      9         2       0.075516   0.04878     0.077908  0.565159
9     10         2       0.075516   0.04878     0.077908  0.589056
10    25         2       0.075796   0.04878     0.078188  0.645236
11    50         2       0.075861   0.04878     0.078254  0.676700
12    75         2       0.075874   0.04878     0.078267  0.695437
13   100         2       0.075874   0.04878     0.078267  0.728204
14   150         2       0.075874   0.04878     0.078267  0.745968
15   200         2       0.075874   0.04878     0.078267  0.781852
16   300         2       0.075874   0.04878     0.078267  0.778823
17   400         2       0.075874   0.04878     0.078267  0.780431
18   500         2       0.075874   0.04878     0.078267  0.805462
19   750         2       0.075874   0.04878     0.078267  0.857757

In [44]:
res_df.to_pickle('./Output/exp1_coef_1-750_numIter_2.pkl')

---

---

In [45]:
shutil.copy2('./../../myCBR_projects/userKnowledgeModeling_yedek.prj', './../../myCBR_projects/userKnowledgeModeling.prj') # complete target filename given

In [47]:
# Set random seed
random_state = random.randint(0, 100)

# Concept name
concept = 'knowledge'
column_names = ['STG','SCG','STR','LPR','PEG','UNS']
class_names = ['0','1','2','3']
cat_feat = []

# Read data
train = pd.read_pickle('./Data/unm_train.pkl')
test =  pd.read_pickle('./Data/unm_test.pkl')

train_cols = train.columns[0:-1]
label = train.columns[-1]

X_train, X_test, y_train, y_test = train[train_cols], test[train_cols], train[[label]], test[[label]]

In [48]:
def rev(dic):
    return {v: k for k, v in dic.items()}

# from categoric features to numeric features with maps
# from numeric features to categoric features with inv_maps
def encode(df, maps):
    for i in cat_feat:
        df[i] = df[i].map(maps[i]).astype('float')
    return df

maps = {}
inv_maps = {}

# encoding for training the model
#X_en = encode(X.copy(), maps)
X_train_en, X_test_en = encode(X_train.copy(), maps), encode(X_test.copy(), maps)
train_en = encode(train.copy(), maps)
test_en = encode(test.copy(), maps)

# load model
model = pickle.load(open('./Model/model_GBC.pkl', "rb"))

# load shap_df
shap_df = pd.read_pickle("./temp_files/shap_df.pkl")

In [49]:
num_iter = 3
explainer = Explainer(model, X_train, X_test, y_train, y_test, label, cat_feat, concept, shap_df=shap_df, maps=maps, inv_maps=inv_maps, num_iter=num_iter)

Given Shap values used.

API connection completed.

Concept names:  ['knowledge']  Is correct:  True

Casebase names:  [['cb_class1'], ['cb_class0'], ['cb_class3'], ['cb_class2']]

Cases deleted from concept 'knowledge': True

Cases imported to the casebases.

Amalgamation functions created for every class using shap values.

In [50]:
res_list_names = ['coef', 'num_iter', 'dissimilarity', 'sparsity', 'instability', 'time']
res_list = []


for coef in [1,2,3,4,5,6,7,8,9,10,25,50,75,100,150,200,300,400,500,750]:
    _, res = explainer.testGenerateCF(coef_thresh = coef)
    res_list.append([coef]+[num_iter]+res)

res_df = pd.DataFrame(res_list,columns=res_list_names)

1
2
3
4
5
6
7
8
9
10
25
50
75
100
150
200
300
400
500
750

In [51]:
res_df

    coef  num_iter  dissimilarity  sparsity  instability      time
0      1         3       0.071106   0.04878     0.073475  0.474685
1      2         3       0.071106   0.04878     0.073475  0.435696
2      3         3       0.071106   0.04878     0.073475  0.428298
3      4         3       0.071106   0.04878     0.073475  0.465765
4      5         3       0.071106   0.04878     0.073475  0.468190
5      6         3       0.071106   0.04878     0.073475  0.521809
6      7         3       0.071106   0.04878     0.073475  0.540230
7      8         3       0.071106   0.04878     0.073475  0.563837
8      9         3       0.071106   0.04878     0.073475  0.593653
9     10         3       0.071106   0.04878     0.073475  0.634442
10    25         3       0.071439   0.04878     0.073807  0.680268
11    50         3       0.071435   0.04878     0.073800  0.716616
12    75         3       0.071449   0.04878     0.073814  0.734729
13   100         3       0.071430   0.04878     0.073795  0.769237
14   150         3       0.071418   0.04878     0.073783  0.810730
15   200         3       0.071424   0.04878     0.073789  0.842594
16   300         3       0.071419   0.04878     0.073785  0.885601
17   400         3       0.071419   0.04878     0.073785  0.911458
18   500         3       0.071419   0.04878     0.073785  0.928632
19   750         3       0.071419   0.04878     0.073785  0.964693

In [52]:
res_df.to_pickle('./Output/exp1_coef_1-750_numIter_3.pkl')

---

In [53]:
shutil.copy2('./../../myCBR_projects/userKnowledgeModeling_yedek.prj', './../../myCBR_projects/userKnowledgeModeling.prj') # complete target filename given

In [55]:
# Set random seed
random_state = random.randint(0, 100)

# Concept name
concept = 'knowledge'
column_names = ['STG','SCG','STR','LPR','PEG','UNS']
class_names = ['0','1','2','3']
cat_feat = []

# Read data
train = pd.read_pickle('./Data/unm_train.pkl')
test =  pd.read_pickle('./Data/unm_test.pkl')

train_cols = train.columns[0:-1]
label = train.columns[-1]

X_train, X_test, y_train, y_test = train[train_cols], test[train_cols], train[[label]], test[[label]]

In [56]:
def rev(dic):
    return {v: k for k, v in dic.items()}

# from categoric features to numeric features with maps
# from numeric features to categoric features with inv_maps
def encode(df, maps):
    for i in cat_feat:
        df[i] = df[i].map(maps[i]).astype('float')
    return df

maps = {}
inv_maps = {}

# encoding for training the model
#X_en = encode(X.copy(), maps)
X_train_en, X_test_en = encode(X_train.copy(), maps), encode(X_test.copy(), maps)
train_en = encode(train.copy(), maps)
test_en = encode(test.copy(), maps)

# load model
model = pickle.load(open('./Model/model_GBC.pkl', "rb"))

# load shap_df
shap_df = pd.read_pickle("./temp_files/shap_df.pkl")

In [59]:
num_iter = 4
explainer = Explainer(model, X_train, X_test, y_train, y_test, label, cat_feat, concept, shap_df=shap_df, maps=maps, inv_maps=inv_maps, num_iter=num_iter)

Given Shap values used.

API connection completed.

Concept names:  ['knowledge']  Is correct:  True

Casebase names:  [['cb_class1'], ['cb_class0'], ['cb_class3'], ['cb_class2']]

Cases deleted from concept 'knowledge': True

Cases imported to the casebases.

Amalgamation functions created for every class using shap values.

In [60]:
res_list_names = ['coef', 'num_iter', 'dissimilarity', 'sparsity', 'instability', 'time']
res_list = []


for coef in [1,2,3,4,5,6,7,8,9,10,25,50,75,100,150,200,300,400,500,750]:
    _, res = explainer.testGenerateCF(coef_thresh = coef)
    res_list.append([coef]+[num_iter]+res)

res_df = pd.DataFrame(res_list,columns=res_list_names)

1
2
3
4
5
6
7
8
9
10
25
50
75
100
150
200
300
400
500
750

In [61]:
res_df

    coef  num_iter  dissimilarity  sparsity  instability      time
0      1         4       0.065938   0.04878     0.068514  0.536162
1      2         4       0.065938   0.04878     0.068514  0.529371
2      3         4       0.065938   0.04878     0.068514  0.512339
3      4         4       0.065938   0.04878     0.068514  0.516474
4      5         4       0.065938   0.04878     0.068514  0.525339
5      6         4       0.065938   0.04878     0.068514  0.542184
6      7         4       0.065938   0.04878     0.068514  0.570474
7      8         4       0.065938   0.04878     0.068514  0.602464
8      9         4       0.065938   0.04878     0.068514  0.611367
9     10         4       0.065938   0.04878     0.068514  0.626300
10    25         4       0.066271   0.04878     0.068846  0.678323
11    50         4       0.066332   0.04878     0.068904  0.737753
12    75         4       0.066363   0.04878     0.068935  0.769597
13   100         4       0.066380   0.04878     0.068953  0.823309
14   150         4       0.066368   0.04878     0.068940  0.870082
15   200         4       0.066373   0.04878     0.068946  0.881270
16   300         4       0.066373   0.04878     0.068945  0.939209
17   400         4       0.066380   0.04878     0.068952  0.977097
18   500         4       0.066380   0.04878     0.068952  0.989699
19   750         4       0.066380   0.04878     0.068952  1.030970

In [62]:
res_df.to_pickle('./Output/exp1_coef_1-750_numIter_4.pkl')